INSERT INTO CATEGORY (description) VALUES ('American');
INSERT INTO CATEGORY (description) VALUES ('Italian');
INSERT INTO CATEGORY (description) VALUES ('Mexican');
INSERT INTO CATEGORY (description) VALUES ('Fast Food');
INSERT INTO CATEGORY (description) VALUES ('Vegan');
INSERT INTO CATEGORY (description) VALUES ('Avocado');
INSERT INTO CATEGORY (description) VALUES ('Dip');
INSERT INTO CATEGORY (description) VALUES ('Diner');
INSERT INTO CATEGORY (description) VALUES ('Grill');
INSERT INTO CATEGORY (description) VALUES ('Chicken');
INSERT INTO CATEGORY (description) VALUES ('Quick and easy');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Teaspoon');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Tablespoon');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Cup');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Pinch');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Ounce');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Unit');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Clove');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Pint');